
-- more insertion for tests (generated by chatgpt and tweaked)


-- =========================================================
-- 10 INSERT VALUES FOR EACH TABLE
-- Order respects foreign key dependencies
-- =========================================================

USE ArtConnect;

-- =========================================================
-- ARTISTS
-- =========================================================

INSERT INTO Artists (artist_id, name, bio, birth_year, contact_email, phone, city, website, is_active) VALUES
(51,'Emma Stone','Digital painter from Paris',1992,'emma@mail.com','0600000001','Paris','www.emmastoneart.com',TRUE),
(52,'Lucas Martin','Modern sculptor',1985,'lucas@mail.com','0600000002','Lyon',NULL,TRUE),
(53,'Sofia Bernard','Street artist',1990,'sofia@mail.com','0600000003','Marseille',NULL,TRUE),
(54,'Nathan Lee','Photographer',1988,'nathan@mail.com','0600000004','Nice','www.nathanlee.com',TRUE),
(55,'Olivia Moreau','Watercolor specialist',1995,'olivia@mail.com','0600000005','Bordeaux','www.oliviamoreau.com',TRUE),
(56,'Hugo Petit','Conceptual artist',1982,'hugo@mail.com','0600000006','Toulouse','www.hugopetit.com',FALSE),
(57,'Mia Laurent','Ceramic artist',1993,'mia@mail.com','0600000007','Lille',NULL,TRUE),
(58,'Ethan Dubois','Illustrator',1998,'ethan@mail.com','0600000008','Paris','www.ethandubois.com',TRUE),
(59,'Chloe Garnier','Mixed media artist',1987,'chloe@mail.com','0600000009','Nantes','www.chloegarnier.com',TRUE),
(60,'Leo Fontaine','Abstract painter',1991,'leo@mail.com','0600000010','Strasbourg',NULL,TRUE);

-- =========================================================
-- SOCIAL_MEDIAS
-- =========================================================

INSERT INTO Social_medias (artist_id, platform, account_handle) VALUES
(51,'Instagram','@emma_art'),
(52,'Facebook','LucasSculpt'),
(53,'TikTok','@sofia.street'),
(54,'Instagram','@nathan.photo'),
(55,'Pinterest','OliviaWatercolor'),
(56,'Twitter','@hugoConcept'),
(57,'Instagram','@miaCeramics'),
(58,'Behance','ethan_design'),
(59,'Facebook','ChloeMixedMedia'),
(59,'Instagram','@chloe.mixed');

-- =========================================================
-- DISCIPLINES
-- =========================================================

INSERT INTO Disciplines (discipline_id, name) VALUES
(55,'Ceramics'),
(56,'Illustration'),
(57,'Street Art'),
(58,'Mixed Media'),
(59,'Watercolor'),
(60,'Conceptual Art');

-- =========================================================
-- ARTWORK_TAGS
-- =========================================================

INSERT INTO Artwork_tags (artwork_tag_id, name) VALUES
(53,'Nature'),
(55,'Minimalist'),
(56,'Portrait'),
(58,'Colorful'),
(59,'BlackAndWhite'),
(60,'Surreal');

-- =========================================================
-- GALLERIES
-- =========================================================

INSERT INTO Galleries (gallery_id, name, address, owner_name, contact_phone, rating, website) VALUES
(52,'Urban Gallery','22 Avenue Lyon','Marc Petit','0101010102',4.2,'www.urbangallery.com'),
(53,'Creative House','5 Nice Center','Laura Martin','0101010103',4.5,'www.creativehouse.com'),
(54,'Art Vision','44 Marseille Road','Nina Dubois','0101010104',4.7,'www.artvision.com'),
(55,'Blue Canvas','18 Bordeaux Street','Paul Henry','0101010105',4.1,'www.bluecanvas.com'),
(56,'Gallery Nova','7 Toulouse Square','Emma Laurent','0101010106',4.9,'www.gallerynova.com'),
(57,'Digital Dreams','13 Lille Avenue','Julie Simon','0101010107',4.4,'www.digitaldreams.com'),
(58,'Classic Arts','66 Nantes Road','Victor Hugo','0101010108',3.9,'www.classicarts.com'),
(59,'Open Studio','2 Strasbourg Blvd','Anna Lee','0101010109',4.3,'www.openstudio.com'),
(60,'Visionary Gallery','77 Paris Center','Chris White','0101010110',NULL,NULL);

-- =========================================================
-- COMMUNITY_MEMBERS
-- =========================================================

INSERT INTO Community_members (community_member_id, name, email, birth_year, phone, city, membership_type) VALUES
(51,'Alice Dupont','alice@mail.com',1998,'0700000001','Paris','premium'),
(52,'Marc Leroy','marc@mail.com',1988,'0700000002','Marseille','free'),
(53,'Julie Simon','julie@mail.com',1995,'0700000003','Lyon','premium'),
(54,'Thomas Henry','thomas@mail.com',1992,'0700000004','Nice','premium'),
(55,'Camille Petit','camille@mail.com',1999,'0700000005','Lille','free'),
(56,'Louis Martin','louis@mail.com',1985,'0700000006','Bordeaux','premium'),
(57,'Sarah White','sarah@mail.com',1991,'0700000007','Paris','premium'),
(58,'Kevin Brown','kevin@mail.com',1996,'0700000008','Nantes','free'),
(59,'Eva Green','eva@mail.com',1993,'0700000009','Toulouse','premium'),
(60,'Noah Black','noah@mail.com',1990,'0700000010','Strasbourg','free');

-- =========================================================
-- PRACTICES
-- =========================================================

INSERT INTO Practices (artist_id, discipline_id) VALUES
(51,4),
(52,2),
(53,57),
(54,3),
(55,59),
(56,60),
(57,55),
(58,56),
(59,58),
(60,1);

-- =========================================================
-- ARTWORKS
-- =========================================================

INSERT INTO Artworks (artwork_id, title, creation_year, type, medium, description, price, status, artist_id) VALUES
(51,'Blue Dreams',2022,'Painting','Oil','Abstract blue painting',1200.00,'FOR_SALE',51),
(52,'Iron Soul',2021,'Sculpture','Metal','Industrial sculpture',3500.00,'SOLD',52),
(53,'City Lights',2023,'Street Art','Spray Paint','Urban street art',900.00,'FOR_SALE',53),
(54,'Silent Faces',2020,'Photography','Digital','Portrait photography',700.00,'EXHIBITED',54),
(55,'Ocean Flow',2021,'Painting','Watercolor','Sea inspired work',1100.00,'EXHIBITED',55),
(56,'Mind Maze',2019,'Conceptual','Mixed','Experimental installation',5000.00,'EXHIBITED',56),
(57,'Clay Roots',2022,'Ceramics','Clay','Handmade ceramic art',800.00,'EXHIBITED',57),
(58,'Future Lines',2024,'Illustration','Ink','Sci-fi illustration',650.00,'FOR_SALE',58),
(59,'Color Storm',2023,'Mixed Media','Acrylic','Colorful mixed textures',1700.00,'SOLD',59),
(60,'Golden Silence',2021,'Painting','Acrylic','Minimal abstract painting',2100.00,'FOR_SALE',60);

-- =========================================================
-- DIMENSIONS
-- =========================================================

INSERT INTO Dimensions (artwork_id, length, width, depth) VALUES
(52,50,50,120),
(54,60,40,NULL),
(55,90,70,NULL),
(56,300,300,300),
(57,40,40,60),
(58,50,35,NULL),
(59,150,100,NULL),
(60,110,90,NULL);

-- =========================================================
-- WORKSHOPS
-- =========================================================

INSERT INTO Workshops (workshop_id, title, workshop_date, duration_minutes, max_participant, price, location, description, level, instructor) VALUES
(51,'Intro to Digital Painting','2026-06-15 14:00:00',180,15,90.00,'Paris Studio','Learn digital painting basics','beginner',51),
(52,'Modern Sculpture','2026-06-20 10:00:00',240,10,120.00,'Lyon Center','Metal sculpture workshop','intermediate',52),
(53,'Street Art Session','2026-05-21 10:00:00',150,20,70.00,'Marseille Wall','Urban art techniques','beginner',53),
(54,'Photography Basics','2026-05-21 01:00:00',180,12,80.00,'Nice Studio','Portrait photography','beginner',54),
(55,'Watercolor Masterclass','2024-07-15 13:00:00',200,8,110.00,'Bordeaux Art Room','Advanced watercolor methods','advanced',55),
(56,'Concept Art Thinking','2026-08-01 16:00:00',210,14,95.00,'Toulouse Hub','Conceptual creativity','intermediate',56),
(57,'Ceramic Creations','2026-08-08 11:00:00',240,10,130.00,'Lille Workshop','Clay techniques','advanced',57),
(58,'Illustration for Comics','2026-08-15 10:00:00',180,18,75.00,'Paris Lab','Comic illustration','beginner',58),
(59,'Mixed Media Lab','2026-09-01 14:00:00',220,16,140.00,'Nantes Center','Texture experiments',NULL,59),
(60,'Abstract Painting','2026-09-10 12:00:00',200,15,100.00,'Strasbourg Studio','Abstract composition','intermediate',60);

-- =========================================================
-- EXHIBITIONS
-- =========================================================

INSERT INTO Exhibitions (exhibition_id, title, start_date, end_date, description, curator_name, theme, gallery_id) VALUES
(53,'Urban Colors','2025-07-01','2026-08-01','Street art showcase','Anna White','Urban Life',53),
(54,'Captured Moments','2023-07-15','2023-08-20','Photography exhibition','Laura Green','Portraits',53),
(55,'Water and Light','2026-08-01','2026-09-01','Watercolor works','Paul Simon','Nature',55),
(56,'Ideas Beyond','2026-08-10','2026-09-10','Conceptual artworks','Julie Brown','Philosophy',55),
(57,'Clay Expressions','2026-09-01','2026-10-01','Ceramic exhibition','Chris Martin','Tradition',55),
(58,'Drawn Worlds','2026-09-05','2026-10-10','Illustration showcase','Eva Black','Fantasy',58),
(60,'Silent Gold','2025-10-15','2026-11-20','Abstract paintings','Sophie White','Minimalism',60);

-- =========================================================
-- TAGGED
-- =========================================================

INSERT INTO Tagged (artwork_id, artwork_tag_id) VALUES
(51,1),
(52,3),
(53,2),
(54,56),
(55,53),
(56,4),
(57,55),
(58,58),
(59,60),
(60,60);

-- =========================================================
-- FAVORITE_DISCIPLINES
-- =========================================================

INSERT INTO Favorite_disciplines (discipline_id, community_member_id) VALUES
(1,51),
(2,52),
(3,53),
(4,54),
(55,55),
(56,56),
(57,57),
(58,58),
(59,58);

-- =========================================================
-- BOOKINGS
-- =========================================================

INSERT INTO Bookings (workshop_id, community_member_id, booking_date, payement_status) VALUES
(51,51,'2026-05-01','PAID'),
(52,52,'2026-05-02','PENDING'),
(53,53,'2026-05-03','PAID'),
(54,54,'2026-05-04','PAID'),
(55,55,'2026-05-05','CANCELLED'),
(56,56,'2026-05-06','PENDING'),
(57,57,'2026-05-07','PAID'),
(58,58,'2026-05-08','PAID'),
(59,59,'2026-05-09','PENDING'),
(60,60,'2026-05-10','PAID');

-- =========================================================
-- REVIEWS
-- =========================================================

INSERT INTO Reviews (artwork_id, community_member_id, rating, comment, review_date) VALUES
(51,51,4.5,'Amazing artwork','2026-05-01'),
(52,52,5.0,'Incredible sculpture','2026-05-02'),
(53,53,4.0,'Very creative','2026-05-03'),
(54,54,3.5,'Nice photography','2026-05-04'),
(55,55,4.8,'Beautiful colors','2026-05-05'),
(56,56,4.2,'Thought provoking','2026-05-06'),
(57,57,4.7,'Excellent ceramic work','2026-05-07'),
(58,58,3.9,'Fun illustrations','2026-05-08'),
(59,59,4.6,'Unique textures','2026-05-09'),
(60,60,5.0,'Masterpiece','2026-05-10');

-- =========================================================
-- EXHIBITED
-- =========================================================

INSERT INTO Exhibited (artwork_id, exhibition_id) VALUES
(54,53),
(55,53),
(56,58),
(57,54);

-- =========================================================
-- OPENING_HOURS
-- =========================================================

INSERT INTO Opening_hours (exhibition_id, day, opening_time, closing_time) VALUES
(53,'Monday','09:00:00','18:00:00'),
(53,'Tuesday','10:00:00','19:00:00'),
(53,'Wednesday','09:30:00','18:30:00'),
(55,'Friday','09:00:00','17:00:00'),
(56,'Saturday','10:00:00','22:00:00'),
(57,'Sunday','12:00:00','18:00:00'),
(58,'Monday','08:00:00','16:00:00'),
(60,'Tuesday','09:00:00','21:00:00'),
(60,'Wednesday','10:00:00','20:00:00');
